### PR TITLE
Feature/test project meter runs

### PR DESCRIPTION
**Pull request by philngo**
Addresses an issue in which the project class would not return all recent meter runs - it was overwriting meter runs of one consumption type with meter runs (from the same project) of another consumption type.
 - Update query to use the Manager.raw() SQL query function instead of using a custom connection, updates meter run
 - Still needs tests for the API endpoints which use this recent_meter_runs function. (Old tests didn't catch the problem - and didn't break with these initial commits.)

### CODE REVIEW

**Comment by philngo** [comment]
Those checks failed because the newest version of the eemeter (which they depend on to pass), has not yet been released.

**Comment by marcpareoee** [comment]
Might add a docstring to `recent_meter_runs` that describes the format of the output (looks like you map it to some custom format).

Probably not worth a change, but I probably would have done += to the query strings to add the WHERE and ORDER BY rather than the sort of indirect `format` thing on itself that it does now (was sort of confusing to read at first).

Also, did you test it with multiple projects (to trigger the `if project_pks:` branch)? Doesn't like it glancing through the tests, but perhaps I'm missing it.

**Comment by philngo** [comment]
A docstring would be helpful, I'll add it. It's functionality is non-obvious, and frankly took me a while to figure out as well.

Great, I'm also in favor of += for readability, esp since we are in control and know that we're using the operation on strings. I'll go ahead and make the change. I had just retained the format @evz used orginally (tagged him in case there's something we're not thinking of that could make using `.format(` preferable).

Good catch - I'll add unit tests for that as well. It's tested implicitly in the views, but there's some potentially tricky logic in there (e.g. `.recent_meter_runs()` returns meter runs for _all_ projects, but `.recent_meter_runs(project_pks=[])` returns an empty dict) that makes it all the more important to test explicitly, and that might not be covered in the view tests.

**Comment by philngo** [comment]
BTW, the "tricky" logic above was tricky enough that I got it wrong trying to explain it's trickiness - all the more reason to test it.

**Comment by marcpareoee** [comment]
Forgot to say earlier: nice catch with the test. Glad the review was productive.

**Pull request merged**
